# Generated by Django 3.1.5 on 2021-01-22 16:09

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name='Название категории')),
                ('description', models.TextField(max_length=150, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='NewsTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name='Название тега')),
                ('description', models.TextField(max_length=150, verbose_name='Описание')),
                ('color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_last_change', models.DateTimeField(auto_created=True, verbose_name='Дата последнего редактирования')),
                ('date_of_create', models.DateTimeField(auto_created=True, verbose_name='Дата создания')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, verbose_name='Содержание')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Изображение')),
                ('published', models.BooleanField(default=True, verbose_name='Статус публикации')),
                ('author_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.news', verbose_name='Автор')),
                ('category', models.ManyToManyField(null=True, related_name='news_category', to='news.Categories')),
                ('tags', models.ManyToManyField(null=True, related_name='news_tags', to='news.Categories')),
            ],
        ),
    ]
