# Generated by Django 3.1.5 on 2021-01-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210123_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscategories',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='newstags',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название тега'),
        ),
    ]
